# Pairwise covering-array E2E runner for SerialMonitorEssential
# Applies each row's 8 factor values via UIA, then checks health oracles.
param([string]$LogPath)

Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
$auto = [System.Windows.Automation.AutomationElement]
$ui = "C:\Users\kazuki\AppData\Local\Temp\claude\C--Users-kazuki-Documents-SerialMonitorEssential\38319a3a-0e22-4b3c-bda2-aed9f893fff2\scratchpad\ui.ps1"

function Find-Win([string]$title) {
  $cond = New-Object System.Windows.Automation.PropertyCondition($auto::NameProperty, $title)
  return $auto::RootElement.FindFirst([System.Windows.Automation.TreeScope]::Children, $cond)
}
function Get-Buttons($win) {
  $cond = New-Object System.Windows.Automation.PropertyCondition($auto::ControlTypeProperty, [System.Windows.Automation.ControlType]::Button)
  return $win.FindAll([System.Windows.Automation.TreeScope]::Descendants, $cond)
}
function Click-Btn($win, [string]$name) {
  foreach ($b in (Get-Buttons $win)) {
    if ($b.Current.Name -eq $name -or $b.Current.Name -like "*$name*") {
      $b.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke()
      return $true
    }
  }
  return $false
}
function Get-Checkbox($win, [string]$name) {
  $cond = New-Object System.Windows.Automation.PropertyCondition($auto::ControlTypeProperty, [System.Windows.Automation.ControlType]::CheckBox)
  foreach ($cb in $win.FindAll([System.Windows.Automation.TreeScope]::Descendants, $cond)) {
    if ($name -eq "" -and [string]::IsNullOrEmpty($cb.Current.Name)) { return $cb }
    if ($name -ne "" -and $cb.Current.Name -like "*$name*") { return $cb }
  }
  return $null
}
function Ensure-Toggle($win, [string]$name, [bool]$desired) {
  $cb = Get-Checkbox $win $name
  if ($null -eq $cb) { throw "checkbox '$name' not found" }
  for ($i = 0; $i -lt 3; $i++) {
    $tp = $cb.GetCurrentPattern([System.Windows.Automation.TogglePattern]::Pattern)
    $isOn = ($tp.Current.ToggleState -eq [System.Windows.Automation.ToggleState]::On)
    if ($isOn -eq $desired) { return }
    $tp.Toggle()
    Start-Sleep -Milliseconds 400
  }
  $tp = $cb.GetCurrentPattern([System.Windows.Automation.TogglePattern]::Pattern)
  $isOn = ($tp.Current.ToggleState -eq [System.Windows.Automation.ToggleState]::On)
  if ($isOn -ne $desired) { throw "checkbox '$name' did not reach $desired" }
}
function Get-StatusTexts($win) {
  $out = @()
  $all = $win.FindAll([System.Windows.Automation.TreeScope]::Descendants, [System.Windows.Automation.Condition]::TrueCondition)
  foreach ($e in $all) { $n = $e.Current.Name; if ($n) { $out += $n } }
  return $out
}

# Covering array (generated by pairwise_gen.py, all 112 pairs)
$rows = @(
  @{connected="yes"; viewMode="hex";   lineWrap="off"; timestamp="on";  autoScroll="on";  plotterOpen="yes"; aggMode="LTTB";    plotView="paused"},
  @{connected="no";  viewMode="ascii"; lineWrap="on";  timestamp="off"; autoScroll="off"; plotterOpen="yes"; aggMode="Average"; plotView="live"},
  @{connected="no";  viewMode="hex";   lineWrap="on";  timestamp="on";  autoScroll="on";  plotterOpen="no";  aggMode="Average"; plotView="paused"},
  @{connected="yes"; viewMode="ascii"; lineWrap="on";  timestamp="off"; autoScroll="on";  plotterOpen="no";  aggMode="LTTB";    plotView="live"},
  @{connected="yes"; viewMode="hex";   lineWrap="off"; timestamp="off"; autoScroll="off"; plotterOpen="no";  aggMode="Average"; plotView="paused"},
  @{connected="no";  viewMode="hex";   lineWrap="off"; timestamp="on";  autoScroll="off"; plotterOpen="yes"; aggMode="LTTB";    plotView="live"},
  @{connected="yes"; viewMode="ascii"; lineWrap="off"; timestamp="on";  autoScroll="on";  plotterOpen="yes"; aggMode="LTTB";    plotView="paused"}
)

$results = @()
$rowNum = 0
foreach ($row in $rows) {
  $rowNum++
  $failures = @()
  $logStart = (Get-Content $LogPath -ErrorAction SilentlyContinue | Measure-Object -Line).Lines
  try {
    $main = Find-Win "Serial Monitor Essential"
    if ($null -eq $main) { throw "main window missing" }

    # --- connected ---
    $connectBtnNames = (Get-Buttons $main) | ForEach-Object { $_.Current.Name }
    $isConnected = $connectBtnNames -contains "Disconnect"
    if ($row.connected -eq "yes" -and -not $isConnected) { [void](Click-Btn $main "Connect"); Start-Sleep -Seconds 1 }
    if ($row.connected -eq "no" -and $isConnected) { [void](Click-Btn $main "Disconnect"); Start-Sleep -Seconds 1 }

    # --- viewMode (unnamed checkbox: On=ascii) ---
    Ensure-Toggle $main "" ($row.viewMode -eq "ascii")
    Start-Sleep -Milliseconds 300

    # --- ascii-only toggles (skip when hex: disabled) ---
    if ($row.viewMode -eq "ascii") {
      Ensure-Toggle $main "Line Wrap" ($row.lineWrap -eq "on")
      Ensure-Toggle $main "Timestamp" ($row.timestamp -eq "on")
    }
    Ensure-Toggle $main "Auto Scroll" ($row.autoScroll -eq "on")

    # --- plotterOpen ---
    $plotter = Find-Win "Serial Plotter"
    if ($row.plotterOpen -eq "yes" -and $null -eq $plotter) {
      [void](Click-Btn $main "Plotter"); Start-Sleep -Seconds 3
      $plotter = Find-Win "Serial Plotter"
    }
    if ($row.plotterOpen -eq "no" -and $null -ne $plotter) {
      $plotter.GetCurrentPattern([System.Windows.Automation.WindowPattern]::Pattern).Close()
      Start-Sleep -Seconds 2
      $plotter = Find-Win "Serial Plotter"
    }

    if ($row.plotterOpen -eq "yes") {
      if ($null -eq $plotter) { throw "plotter window failed to open" }
      # --- aggMode ---
      & $ui -Action select-combo -WindowTitle "Serial Plotter" -Path "LTTB|Average" -Name ("^" + $row.aggMode + "$") | Out-Null
      Start-Sleep -Milliseconds 500
      # --- plotView ---
      $pbtns = (Get-Buttons $plotter) | ForEach-Object { $_.Current.Name }
      $isPaused = ($pbtns | Where-Object { $_ -like "*Resume*" }).Count -gt 0
      if ($row.plotView -eq "paused" -and -not $isPaused) { [void](Click-Btn $plotter "Pause") }
      if ($row.plotView -eq "live" -and $isPaused) { [void](Click-Btn $plotter "Resume") }
      Start-Sleep -Milliseconds 800

      # Oracle: footer status matches
      $texts = Get-StatusTexts $plotter
      if ($row.plotView -eq "paused" -and -not ($texts -match "Paused")) { $failures += "status not Paused" }
      if ($row.plotView -eq "live" -and -not ($texts -match "LIVE|Inspect")) { $failures += "status not LIVE" }
    } else {
      if ($null -ne $plotter) { $failures += "plotter window failed to close" }
    }

    # Oracle: app process alive
    try { $null = Get-Process -Name "tauri-appserial-monitor-essential","serial-monitor-essential" -ErrorAction Stop } catch { $failures += "app process died" }

    # Oracle: no new panic/ERROR in log
    $logNow = Get-Content $LogPath -ErrorAction SilentlyContinue
    if ($logNow) {
      $newLines = $logNow | Select-Object -Skip $logStart
      $bad = $newLines | Where-Object { $_ -match "panicked|ERROR" }
      if ($bad) { $failures += ("log errors: " + ($bad -join " / ")) }
    }
  } catch {
    $failures += ("EXCEPTION: " + $_.Exception.Message)
  }

  $status = if ($failures.Count -eq 0) { "PASS" } else { "FAIL: " + ($failures -join "; ") }
  $desc = ($row.GetEnumerator() | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Value)" }) -join " "
  $results += "Row ${rowNum}: $status  [$desc]"
  Write-Host ("Row ${rowNum}: $status")
}

Write-Host "===== SUMMARY ====="
$results | ForEach-Object { Write-Host $_ }
