[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = ["-C", "link-arg=--nmagic", "-C", "link-arg=-Tlink.x"]
# BOOTSEL モードの Pico へ直接書き込む (cargo install elf2uf2-rs)
runner = "elf2uf2-rs -d"
